### ISSUE TITLE
CTS/VTS Execution and results

### ISSUE THREAD

**Issue by rsglobal** [GloDroid/glodroid_manifest#2]
Pinephone VTS results on v0.6.1 are available:[HERE]( https://github.com/GloDroid/glodroid_manifest/releases/download/v0.6.1/gd-v0.6.1-pinephone-vts-results.tar.gz)

**Comment by rsglobal** [comment]
v0.1.0 crash during CTS related to gralloc


```
02-19 14:08:42.011 13111 13141 D VirtualDisplayTest: New image available from virtual display.
02-19 14:08:42.011 13111 13141 I GRALLOC-GBM: lock bo 0xae11e798, cnt=0, usage=3
02-19 14:08:42.011 13111 13141 W Gralloc2: lock(0x98bb5820, ...) failed: 3
02-19 14:08:42.011 13111 13141 E AndroidMediaUtils: Lock buffer failed!
02-19 14:08:42.011 13111 13141 E AndroidMediaUtils: lockImageFromBuffer: lock graphic buffer failed
02-19 14:08:42.013 13111 13141 E AndroidRuntime: FATAL EXCEPTION: TestHandler
02-19 14:08:42.013 13111 13141 E AndroidRuntime: Process: android.display.cts, PID: 13111
02-19 14:08:42.013 13111 13141 E AndroidRuntime: java.lang.RuntimeException: lock buffer failed for format 0x1
02-19 14:08:42.013 13111 13141 E AndroidRuntime: 	at android.media.ImageReader$SurfaceImage.nativeCreatePlanes(Native Method)
02-19 14:08:42.013 13111 13141 E AndroidRuntime: 	at android.media.ImageReader$SurfaceImage.getPlanes(ImageReader.java:898)
02-19 14:08:42.013 13111 13141 E AndroidRuntime: 	at android.display.cts.VirtualDisplayTest$ImageListener.scanImage(VirtualDisplayTest.java:381)
02-19 14:08:42.013 13111 13141 E AndroidRuntime: 	at android.display.cts.VirtualDisplayTest$ImageListener.onImageAvailable(VirtualDisplayTest.java:364)
02-19 14:08:42.013 13111 13141 E AndroidRuntime: 	at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:798)
02-19 14:08:42.013 13111 13141 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
02-19 14:08:42.013 13111 13141 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
02-19 14:08:42.013 13111 13141 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
02-19 14:08:42.037   370 13144 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
```

**Comment by rsglobal** [comment]
Pinephone VTS results on v0.6.1 is available:[HERE]( https://github.com/GloDroid/glodroid_manifest/releases/download/v0.6.1/gd-v0.6.1-pinephone-vts-results.tar.gz)

```
Total Tests       : 6449
PASSED            : 6023
FAILED            : 96
IGNORED           : 178
ASSUMPTION_FAILURE: 34
```
