### ISSUE TITLE
cannot build on kubuntu 20.04

### ISSUE THREAD

**Issue by mzramna** [GloDroid/glodroid_manifest#46]
if i try to run `sudo repo init -u https://github.com/glodroid/glodroid_manifest` in kubuntu 20.04 this is what it shows
```
warning: gpg (GnuPG) is not available.
warning: Installing it is strongly encouraged.

warning: templates not found /build/git-repo-publish/parts/git/install/usr/share/git-core/templates
Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
Traceback (most recent call last):
  File "/home/_______/GloDroid/.repo/repo/main.py", line 49, in <module>
    import event_log
  File "/home/_______/GloDroid/.repo/repo/event_log.py", line 167, in <module>
    _EVENT_ID = multiprocessing.Value('i', 1)
  File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/__init__.py", line 253, in Value
    return Value(typecode_or_type, *args, **kwds)
  File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/sharedctypes.py", line 108, in Value
    lock = RLock()
  File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/__init__.py", line 183, in RLock
    return RLock()
  File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/synchronize.py", line 172, in __init__
    SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1)
  File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied
```
if i try to run ` sudo ./.repo/repo/main.py` where the error happends this message apear:
```
repo: warning: Python 2 is no longer supported; Please upgrade to Python 3.6+.
no --wrapper-version argument
```
btw: the package `repo` does not exists into apt,just able to install using snap,and package python-dev also does no exist anymore,has been replaced by python-dev-is-python2

**Comment by MaksymPrymierov** [comment]
@mzramna 
Hello, thanks for your report.

 The `repo` app is best used without `sudo`.
> `sudo repo init -u https://github.com/glodroid/glodroid_manifest`

Try to install python3 `sudo apt install python3`
> repo: warning: Python 2 is no longer supported; Please upgrade to Python 3.6+.
no --wrapper-version argument

We will update the build and fetch steps.
> btw: the package repo does not exists into apt,just able to install using snap,and package python-dev also does no exist anymore,has been replaced by python-dev-is-python2
